on:
  push:
    branches:
      - master

name: Package

defaults:
  run:
    shell: bash

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Package
        run: |
          npm ci
          npm test
          npm run all
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "(chore) updating dist" || echo "No changes to commit"
          git push origin HEAD:master
